=== PablodelaRosa07/LDM/Pablo_delaRosa_AE_U6.1/Ejercicio3/xsd.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:element name="gestion_comercial">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="tienda" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="nombreTienda" type="xs:string"/>
              <xs:element name="ubicacion" type="xs:string"/> <xs:element name="empleado" type="xs:string" maxOccurs="unbounded"/>
              
              <xs:element name="catalogo">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="movil" maxOccurs="unbounded">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="marca" type="xs:string"/>
                          <xs:element name="modelo" type="xs:string"/>
                          <xs:element name="fabricante" type="xs:string"/>
                          <xs:element name="precio" type="xs:string"/>
                          <xs:element name="fechaLanzamiento" type="xs:string"/>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

</xs:schema>

=== PablodelaRosa07/LDM/Pablo_delaRosa_AE_U6.1/Ejercicio3/xml2.xml
<?xml version="1.0" encoding="UTF-8"?>
<gestion_comercial xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="xsd.xsd">
  <tienda>
    <nombreTienda>Web Oficial Móviles</nombreTienda>
    <ubicacion>Online</ubicacion>
    <empleado>Soporte Técnico Web</empleado>
    <catalogo>
      <movil>
        <marca>Apple</marca>
        <modelo>iPhone 15 Pro</modelo>
        <fabricante>Apple Inc.</fabricante>
        <precio>1200 euros</precio>
        <fechaLanzamiento>Septiembre 2023</fechaLanzamiento>
      </movil>
    </catalogo>
  </tienda>
</gestion_comercial>

=== PablodelaRosa07/LDM/Pablo_delaRosa_AE_U6.1/Ejercicio3/xml1.xml
<?xml version="1.0" encoding="UTF-8"?>
<gestion_comercial xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="xsd.xsd">
  <tienda>
    <nombreTienda>Mobile Nervión</nombreTienda>
    <ubicacion>Física - Sevilla</ubicacion>
    <empleado>Juan Pérez</empleado>
    <empleado>María García</empleado>
    <catalogo>
      <movil>
        <marca>Xiaomi</marca>
        <modelo>Redmi Note 12 Pro</modelo>
        <fabricante>Xiaomi Corp</fabricante>
        <precio>250 euros</precio>
        <fechaLanzamiento>Enero 2023</fechaLanzamiento>
      </movil>
    </catalogo>
  </tienda>
</gestion_comercial>
