=== PablodelaRosa07/LDM/Pablo_delaRosa_AE_U6.1/Ejercicio5/xsd.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:element name="agencia_alquiler">
    <xs:complexType>
      <xs:sequence>
        
        <xs:element name="alquiler" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="oficina" type="xs:string"/>
              <xs:element name="empleado" type="xs:string"/>
              
              <xs:element name="cliente" type="xs:string"/>
              <xs:element name="dniCliente" type="xs:string"/>
              
              <xs:element name="vehiculo">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="marca" type="xs:string"/> <xs:element name="modelo" type="xs:string"/> <xs:element name="matricula" type="xs:string"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              
              <xs:element name="fechaAlquiler" type="xs:string"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>

      </xs:sequence>
    </xs:complexType>
  </xs:element>

</xs:schema>

=== PablodelaRosa07/LDM/Pablo_delaRosa_AE_U6.1/Ejercicio5/xml2.xml
<?xml version="1.0" encoding="UTF-8"?>
<agencia_alquiler xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="xsd.xsd">
  <alquiler>
    <oficina>Sucursal Santa Justa</oficina>
    <empleado>Laura Beltrán</empleado>
    <cliente>Mudanzas Paco</cliente>
    <dniCliente>B99887766</dniCliente>
    <vehiculo>
      <marca>Mercedes-Benz (Origen: Alemania)</marca>
      <modelo>Sprinter (Fab: 2023)</modelo>
      <matricula>9988-XYZ</matricula>
    </vehiculo>
    <fechaAlquiler>20/05/2024</fechaAlquiler>
  </alquiler>
</agencia_alquiler>

=== PablodelaRosa07/LDM/Pablo_delaRosa_AE_U6.1/Ejercicio5/xml1.xml
<?xml version="1.0" encoding="UTF-8"?>
<agencia_alquiler xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="xsd.xsd">
  <alquiler>
    <oficina>Sede Aeropuerto Sevilla</oficina>
    <empleado>Carlos Ruiz</empleado>
    <cliente>Ana López</cliente>
    <dniCliente>12345678A</dniCliente>
    <vehiculo>
      <marca>Toyota (Origen: Japón)</marca>
      <modelo>Yaris (Fab: 2022)</modelo>
      <matricula>1122-ABC</matricula>
    </vehiculo>
    <fechaAlquiler>15/05/2024</fechaAlquiler>
  </alquiler>
</agencia_alquiler>
