=== PablodelaRosa07/LDM/Pablo_delaRosa_AE_U6.1/Ejercicio2/xsd.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:element name="gestion_prestamos">
    <xs:complexType>
      <xs:sequence>
        
        <xs:element name="prestamo" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="codigoAlumno" type="xs:string"/>
              <xs:element name="tipoEstudios" type="xs:string"/> <xs:element name="tipoMaterial" type="xs:string"/> <xs:element name="nombreMaterial" type="xs:string"/>
              
              <xs:element name="sedeRetirada" type="xs:string"/> <xs:element name="diasPrestamo" type="xs:string"/> 
              <xs:element name="estado" type="xs:string"/> </xs:sequence>
          </xs:complexType>
        </xs:element>

      </xs:sequence>
    </xs:complexType>
  </xs:element>

</xs:schema>

=== PablodelaRosa07/LDM/Pablo_delaRosa_AE_U6.1/Ejercicio2/xml1.xml
<?xml version="1.0" encoding="UTF-8"?>
<gestion_prestamos xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="xsd.xsd">
  <prestamo>
    <codigoAlumno>ALU-8822</codigoAlumno>
    <tipoEstudios>Máster</tipoEstudios>
    <tipoMaterial>Libro</tipoMaterial>
    <nombreMaterial>Guía de XML Avanzado</nombreMaterial>
    <sedeRetirada>Porvenir</sedeRetirada>
    <diasPrestamo>7 días</diasPrestamo>
    <estado>Activo</estado>
  </prestamo>
</gestion_prestamos>

=== PablodelaRosa07/LDM/Pablo_delaRosa_AE_U6.1/Ejercicio2/xml2.xml
<?xml version="1.0" encoding="UTF-8"?>
<gestion_prestamos xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="xsd.xsd">
  <prestamo>
    <codigoAlumno>ALU-4455</codigoAlumno>
    <tipoEstudios>Grado Superior</tipoEstudios>
    <tipoMaterial>Cámara</tipoMaterial>
    <nombreMaterial>Canon 3D</nombreMaterial>
    <sedeRetirada>Cartuja</sedeRetirada>
    <diasPrestamo>3 días</diasPrestamo>
    <estado>Devuelto</estado>
  </prestamo>
</gestion_prestamos>
