=== PablodelaRosa07/LDM/Pablo_delaRosa_AE_U5.1/Ejercicio4/Empresa.dtd
<!ELEMENT empresa (sedes, proyectos)>
<!ELEMENT sedes (sede+)>
<!ELEMENT sede (departamento+)>
<!ATTLIST sede nombre CDATA #REQUIRED>

<!ELEMENT departamento (programadores)>
<!ATTLIST departamento nombre (movil|videojuegos|ERP) #REQUIRED>

<!ELEMENT programadores (senior+)>
<!ELEMENT senior (junior*)>
<!ATTLIST senior 
          id ID #REQUIRED
          nombre CDATA #REQUIRED>
<!ELEMENT junior EMPTY>
<!ATTLIST junior 
          id ID #REQUIRED
          nombre CDATA #REQUIRED>

<!ELEMENT proyectos (proyecto+)>
<!ELEMENT proyecto (equipo, subproyecto*)>
<!ATTLIST proyecto 
          id_pro ID #REQUIRED
          nombre CDATA #REQUIRED>
<!ELEMENT equipo (miembro+)>
<!ELEMENT miembro EMPTY>
<!ATTLIST miembro ref_prog IDREF #REQUIRED>

<!ELEMENT subproyecto EMPTY>
<!ATTLIST subproyecto nombre CDATA #REQUIRED>

=== PablodelaRosa07/LDM/Pablo_delaRosa_AE_U5.1/Ejercicio4/CasoA.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE empresa SYSTEM "Empresa.dtd">
<empresa>
    <sedes>
        <sede nombre="Málaga Tech">
            <departamento nombre="movil">
                <programadores>
                    <senior id="S01" nombre="Laura Jefa">
                        <junior id="J01" nombre="Pedro Novato"/>
                        <junior id="J02" nombre="Marta Aprendiz"/>
                    </senior>
                </programadores>
            </departamento>
        </sede>
    </sedes>
    <proyectos>
        <proyecto id_pro="P_APP_01" nombre="App Bancaria">
            <equipo>
                <miembro ref_prog="S01"/>
                <miembro ref_prog="J01"/>
            </equipo>
            <subproyecto nombre="Modulo Login"/>
        </proyecto>
    </proyectos>
</empresa>

=== PablodelaRosa07/LDM/EXAMEN LDM/xml_dtd/Ejercicio4/CasoB.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE empresa SYSTEM "Empresa.dtd">
<empresa>
    <sedes>
        <sede nombre="Sevilla Games">
            <departamento nombre="videojuegos">
                <programadores>
                    <senior id="S_GAMES_01" nombre="Antonio Moreno">
                        <junior id="J_GAMES_01" nombre="Lucía Ferrera"/>
                        <junior id="J_GAMES_02" nombre="Fran Gómez"/>
                    </senior>
                </programadores>
            </departamento>
        </sede>
    </sedes>
    <proyectos>
        <proyecto id_pro="PRO_SIM_VUELO" nombre="Simulador Vuelo">
            <equipo>
                <miembro ref_prog="S_GAMES_01"/>
                <miembro ref_prog="J_GAMES_01"/>
            </equipo>
            <subproyecto nombre="IA de Navegación"/>
        </proyecto>
    </proyectos>
</empresa>
