=== PablodelaRosa07/LDM/Pablo_delaRosa_AE_U5.1/Ejercicio8/concesionarios.dtd
<!ENTITY copy_legal "Propiedad de Red Concesionarios S.A. 2026.">

<!ELEMENT concesionarios (info_legal, repuestos, concesionario+)>

<!ELEMENT info_legal (#PCDATA)>

<!ELEMENT repuestos (pieza+)>
<!ELEMENT pieza (#PCDATA)>
<!ATTLIST pieza id ID #REQUIRED>

<!ELEMENT concesionario (vehiculo*)>
<!ATTLIST concesionario 
          nombre CDATA #REQUIRED
          ciudad CDATA #FIXED "Madrid">

<!ELEMENT vehiculo (modelo, equipamiento, precio)>
<!ATTLIST vehiculo 
          id ID #REQUIRED
          marca CDATA #REQUIRED
          combustible (gasolina | diesel | electrico | hibrido) "gasolina">

<!ELEMENT modelo (#PCDATA)>

<!ELEMENT equipamiento EMPTY>
<!ATTLIST equipamiento piezas_ref IDREFS #REQUIRED>

<!ELEMENT precio (#PCDATA)>
<!ATTLIST precio moneda CDATA #FIXED "EUR">

=== PablodelaRosa07/LDM/Pablo_delaRosa_AE_U5.1/Ejercicio8/CasoA.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE concesionarios SYSTEM "concesionarios.dtd">
<concesionarios>
  <info_legal>&copy_legal;</info_legal>

  <repuestos>
    <pieza id="P001">Motor V6</pieza>
    <pieza id="P002">Frenos Cerámicos</pieza>
    <pieza id="P003">Llantas Aleación</pieza>
  </repuestos>

  <concesionario nombre="Centro Ciudad" ciudad="Madrid">
    <vehiculo id="V10" marca="Audi" combustible="gasolina">
      <modelo>A4</modelo>
      <equipamiento piezas_ref="P001 P002" />
      <precio moneda="EUR">45000</precio>
    </vehiculo>
    
    <vehiculo id="V20" marca="Tesla" combustible="electrico">
      <modelo>Model 3</modelo>
      <equipamiento piezas_ref="P003" />
      <precio moneda="EUR">52000</precio>
    </vehiculo>
  </concesionario>
</concesionarios>
