=== PablodelaRosa07/LDM/Pablo_delaRosa_AE_U5.1/Ejercicio6/Catalogo.dtd
<!ELEMENT catalogo (videojuego+)>
<!ELEMENT videojuego (titulo, desarrollador, lanzamiento, plataforma+, precio)>

<!ATTLIST videojuego 
          id ID #REQUIRED
          genero (rpg | accion | deportes | aventura) "aventura">

<!ELEMENT titulo (#PCDATA)>
<!ELEMENT desarrollador (#PCDATA)>

<!ELEMENT lanzamiento EMPTY>
<!ATTLIST lanzamiento anio CDATA #REQUIRED>

<!ELEMENT plataforma (#PCDATA)>

<!ELEMENT precio (#PCDATA)>
<!ATTLIST precio moneda CDATA #FIXED "EUR">

=== PablodelaRosa07/LDM/EXAMEN LDM/xml_dtd/Ejercicio6/CasoA.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE catalogo SYSTEM "catalogo.dtd">
<catalogo>
  <videojuego id="v01" genero="rpg">
    <titulo>The Witcher 3</titulo>
    <desarrollador>CD Projekt Red</desarrollador>
    <lanzamiento anio="2015" />
    <plataforma>PC</plataforma>
    <plataforma>PS4</plataforma>
    <precio moneda="EUR">29.99</precio>
  </videojuego>

  <videojuego id="v02" genero="accion">
    <titulo>Elden Ring</titulo>
    <desarrollador>FromSoftware</desarrollador>
    <lanzamiento anio="2022" />
    <plataforma>Xbox Series X</plataforma>
    <precio moneda="EUR">59.99</precio>
  </videojuego>
</catalogo>
