=== PablodelaRosa07/LDM/Pablo_delaRosa_AE_U6.1/Ejercicio4/xsd.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:element name="organizacion_software">
    <xs:complexType>
      <xs:sequence>
        
        <xs:element name="departamento" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="nombreDepartamento" type="xs:string"/> <xs:element name="sede" type="xs:string"/>
              
              <xs:element name="programadores">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="programador" maxOccurs="unbounded">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="nombre" type="xs:string"/>
                          <xs:element name="nivel" type="xs:string"/> <xs:element name="mentor" type="xs:string" minOccurs="0"/> </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>

              <xs:element name="proyectos">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="proyecto" maxOccurs="unbounded">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="nombreProyecto" type="xs:string"/>
                          <xs:element name="subproyecto" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>

            </xs:sequence>
          </xs:complexType>
        </xs:element>

      </xs:sequence>
    </xs:complexType>
  </xs:element>

</xs:schema>

=== PablodelaRosa07/LDM/Pablo_delaRosa_AE_U6.1/Ejercicio4/xml2.xml
<?xml version="1.0" encoding="UTF-8"?>
<organizacion_software xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="xsd.xsd">
  <departamento>
    <nombreDepartamento>Videojuegos</nombreDepartamento>
    <sede>Cartuja Tecnológica</sede>
    <programadores>
      <programador>
        <nombre>Elena Rodríguez</nombre>
        <nivel>Senior</nivel>
      </programador>
    </programadores>
    <proyectos>
      <proyecto>
        <nombreProyecto>Simulador de Vuelo 2024</nombreProyecto>
        <subproyecto>Motor de Física</subproyecto>
      </proyecto>
    </proyectos>
  </departamento>
</organizacion_software>

=== PablodelaRosa07/LDM/Pablo_delaRosa_AE_U6.1/Ejercicio4/xml1.xml
<?xml version="1.0" encoding="UTF-8"?>
<organizacion_software xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="xsd.xsd">
  <departamento>
    <nombreDepartamento>Desarrollo Móvil</nombreDepartamento>
    <sede>Sevilla Centro</sede>
    <programadores>
      <programador>
        <nombre>Alberto García</nombre>
        <nivel>Senior</nivel>
      </programador>
      <programador>
        <nombre>Lucía Martín</nombre>
        <nivel>Junior</nivel>
        <mentor>Alberto García</mentor>
      </programador>
    </programadores>
    <proyectos>
      <proyecto>
        <nombreProyecto>App Telemedicina</nombreProyecto>
        <subproyecto>Módulo de Citas</subproyecto>
        <subproyecto>Módulo de Videollamada</subproyecto>
      </proyecto>
    </proyectos>
  </departamento>
</organizacion_software>
