=== PablodelaRosa07/LDM/EXAMEN LDM/xml_dtd/Ejercicio3/Tienda.dtd
<!ELEMENT gestion_tiendas (marcas, proveedores, tiendas)>
<!ELEMENT marcas (marca+)>
<!ELEMENT marca (modelo+)>
<!ATTLIST marca 
          nombre CDATA #REQUIRED
          fabricante CDATA #REQUIRED
          localizacion CDATA #REQUIRED>
<!ELEMENT modelo EMPTY>
<!ATTLIST modelo 
          nombre_mod ID #REQUIRED
          fecha_lanzamiento CDATA #REQUIRED
          promo_lanzamiento (si|no) "no">

<!ELEMENT proveedores (proveedor+)>
<!ELEMENT proveedor EMPTY>
<!ATTLIST proveedor 
          cif ID #REQUIRED
          nombre CDATA #REQUIRED>

<!ELEMENT tiendas (tienda+)>
<!ELEMENT tienda (stock+, ventas*)>
<!ATTLIST tienda 
          id ID #REQUIRED
          tipo (fisica|online) #REQUIRED
          ubicacion CDATA #IMPLIED>

<!ELEMENT stock EMPTY>
<!ATTLIST stock 
          modelo_ref IDREF #REQUIRED
          proveedor_ref IDREF #REQUIRED
          precio_actual CDATA #REQUIRED>

<!ELEMENT ventas (venta+)>
<!ELEMENT venta EMPTY>
<!ATTLIST venta 
          modelo_ref IDREF #REQUIRED
          empleado CDATA #REQUIRED
          precio_venta CDATA #REQUIRED
          fecha CDATA #REQUIRED>

=== PablodelaRosa07/LDM/EXAMEN LDM/xml_dtd/Ejercicio3/CasoB.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE gestion_tiendas SYSTEM "Tienda.dtd">
<gestion_tiendas>
    <marcas>
        <marca nombre="Tecno2" fabricante="Tecno2 Corp" localizacion="Nueva York">
            <modelo nombre_mod="S24" fecha_lanzamiento="2024-01-01" promo_lanzamiento="no"/>
        </marca>
    </marcas>
    <proveedores>
        <proveedor cif="B67890" nombre="Global Mobiles"/>
    </proveedores>
    <tiendas>
        <tienda id="T_WEB" tipo="online">
            <stock modelo_ref="S24" proveedor_ref="B67890" precio_actual="850"/>
        </tienda>
    </tiendas>
</gestion_tiendas>

=== PablodelaRosa07/LDM/Pablo_delaRosa_AE_U5.1/Ejercicio3/CasoA.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE gestion_tiendas SYSTEM "Tienda.dtd">
<gestion_tiendas>
    <marcas>
        <marca nombre="Tecno" fabricante="Tecno Inc" localizacion="California">
            <modelo nombre_mod="P15" fecha_lanzamiento="2023-09-12" promo_lanzamiento="si"/>
        </marca>
    </marcas>
    <proveedores>
        <proveedor cif="B12345" nombre="TecnoDistribución S.L."/>
    </proveedores>
    <tiendas>
        <tienda id="T_CENTRO" tipo="fisica" ubicacion="Calle Sierpes, Sevilla">
            <stock modelo_ref="P15" proveedor_ref="B12345" precio_actual="999"/>
        </tienda>
    </tiendas>
</gestion_tiendas>
