=== PablodelaRosa07/LDM/Pablo_delaRosa_AE_U5.1/Ejercicio1/Escuela.dtd
<!ELEMENT escuela (centros, alumnos, docentes)>
<!ELEMENT centros (centro+)>
<!ELEMENT centro (ciclo+)>
<!ATTLIST centro 
          nombre CDATA #REQUIRED
          sede (Cartuja | Montequinto | Jerez) #REQUIRED>

<!ELEMENT ciclo (asignatura+)>
<!ATTLIST ciclo 
          nombre (DAW | DAM) #REQUIRED>

<!ELEMENT asignatura (prerrequisito*)>
<!ATTLIST asignatura 
          id ID #REQUIRED
          nombre CDATA #REQUIRED
          curso (1 | 2) #REQUIRED>

<!ELEMENT prerrequisito EMPTY>
<!ATTLIST prerrequisito 
          ref IDREF #REQUIRED>

<!ELEMENT alumnos (alumno+)>
<!ELEMENT alumno (matricula+)>
<!ATTLIST alumno 
          dni ID #REQUIRED
          nombre CDATA #REQUIRED
          acceso (Bachillerato | Grado_Medio | Prueba_Acceso) #REQUIRED>

<!ELEMENT matricula EMPTY>
<!ATTLIST matricula 
          asignatura IDREF #REQUIRED
          periodo_academico CDATA #REQUIRED>

<!ELEMENT docentes (docente+)>
<!ELEMENT docente (imparte+)>
<!ATTLIST docente 
          dni ID #REQUIRED
          nombre CDATA #REQUIRED>

<!ELEMENT imparte EMPTY>
<!ATTLIST imparte 
          asignatura IDREF #REQUIRED
          anyo CDATA #REQUIRED>

=== PablodelaRosa07/LDM/EXAMEN LDM/xml_dtd/Ejercicio1/CasoA.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE escuela SYSTEM "Escuela.dtd">
<escuela>
    <centros>
        <centro nombre="Sede Tecnológica" sede="Cartuja">
            <ciclo nombre="DAM">
                <asignatura id="BD" nombre="Base de Datos" curso="1"/>
                <asignatura id="DWES" nombre="Desarrollo Web Entorno Servidor" curso="2">
                    <prerrequisito ref="BD"/>
                </asignatura>
            </ciclo>
        </centro>
    </centros>

    <alumnos>
        <alumno dni="DNI12345678X" nombre="Juan Pérez" acceso="Bachillerato"> <!-- Los ID no pueden empezar por números-->
            <matricula asignatura="BD" periodo_academico="2023-2024"/>
            <matricula asignatura="BD" periodo_academico="2024-2025"/>

        </alumno>
    </alumnos>

    <docentes>
        <docente dni="DNI98765432Y" nombre="Ana Martínez">
            <imparte asignatura="BD" anyo="2024"/>
        </docente>
    </docentes>
</escuela>

=== PablodelaRosa07/LDM/EXAMEN LDM/xml_dtd/Ejercicio1/CasoB.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE escuela SYSTEM "Escuela.dtd">
<escuela>
    <centros>
        <centro nombre="Centro Dos Hermanas" sede="Montequinto">
            <ciclo nombre="DAM">
                <asignatura id="PROG" nombre="Programación" curso="1"/>
                <asignatura id="PMDM" nombre="Prog. Multimedia" curso="2">
                    <prerrequisito ref="PROG"/>
                </asignatura>
            </ciclo>
        </centro>
    </centros>

    <alumnos>
        <alumno dni="DNI87654321Z" nombre="María García" acceso="Grado_Medio">
            <matricula asignatura="PROG" periodo_academico="2023-2024"/>
            <matricula asignatura="PROG" periodo_academico="2024-2025"/>
        </alumno>
    </alumnos>

    <docentes>
        <docente dni="DNI11223344K" nombre="Carlos Ruiz">
            <imparte asignatura="PROG" anyo="2024"/>
        </docente>
    </docentes>
</escuela>
