=== PablodelaRosa07/LDM/Pablo_delaRosa_AE_U5.1/Ejercicio5/Alquiler.dtd
<!ELEMENT agencia (marcas, oficinas, empleados, clientes)>
<!ELEMENT marcas (marca+)>
<!ELEMENT marca (modelo+)>
<!ATTLIST marca 
          nombre CDATA #REQUIRED
          origen CDATA #REQUIRED>
<!ELEMENT modelo EMPTY>
<!ATTLIST modelo 
          id_mod ID #REQUIRED
          nombre CDATA #REQUIRED
          anyo CDATA #REQUIRED>

<!ELEMENT oficinas (oficina+)>
<!ELEMENT oficina (vehiculo+)>
<!ATTLIST oficina id ID #REQUIRED ciudad CDATA #REQUIRED>
<!ELEMENT vehiculo EMPTY>
<!ATTLIST vehiculo 
          matricula ID #REQUIRED
          modelo_ref IDREF #REQUIRED>

<!ELEMENT empleados (empleado+)>
<!ELEMENT empleado (curso*)>
<!ATTLIST empleado id ID #REQUIRED nombre CDATA #REQUIRED>
<!ELEMENT curso EMPTY>
<!ATTLIST curso nombre CDATA #REQUIRED fecha CDATA #REQUIRED>

<!ELEMENT clientes (cliente+)>
<!ELEMENT cliente (alquiler+)>
<!ATTLIST cliente dni ID #REQUIRED nombre CDATA #REQUIRED>
<!ELEMENT alquiler EMPTY>
<!ATTLIST alquiler 
          matricula_ref IDREF #REQUIRED
          oficina_ref IDREF #REQUIRED
          empleado_ref IDREF #REQUIRED
          fecha_inicio CDATA #REQUIRED>

=== PablodelaRosa07/LDM/EXAMEN LDM/xml_dtd/Ejercicio5/CasoB.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE agencia SYSTEM "Alquiler.dtd">
<agencia>
    <marcas>
        <marca nombre="Tesla" origen="EEUU">
            <modelo id_mod="MOD3" nombre="Model 3" anyo="2024"/>
            <modelo id_mod="MODY" nombre="Model Y" anyo="2025"/>
        </marca>
    </marcas>
    <oficinas>
        <oficina id="OF_MAD_05" ciudad="Madrid">
            <vehiculo matricula="MAT5566KKB" modelo_ref="MOD3"/>
            <vehiculo matricula="MAT9988ZXY" modelo_ref="MODY"/>
        </oficina>
    </oficinas>
    <empleados>
        <empleado id="E_COMER_22" nombre="Beatriz Solís">
            <curso nombre="Seguridad Vehículos Eléctricos" fecha="2025-11-20"/>
            <curso nombre="Ventas Avanzadas" fecha="2026-01-15"/>
        </empleado>
    </empleados>
    <clientes>
        <cliente dni="DNI12344321P" nombre="Sonia Méndez">
            <alquiler matricula_ref="MAT9988ZXY" oficina_ref="OF_MAD_05" empleado_ref="E_COMER_22" fecha_inicio="2026-03-01"/>
        </cliente>
    </clientes>
</agencia>

=== PablodelaRosa07/LDM/EXAMEN LDM/xml_dtd/Ejercicio5/CasoA.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE agencia SYSTEM "Alquiler.dtd">
<agencia>
    <marcas>
        <marca nombre="Toyota" origen="Japón">
            <modelo id_mod="TOYO" nombre="Toyo Hybrid" anyo="2023"/>
            <modelo id_mod="RAV_4" nombre="RAV4" anyo="2024"/>
        </marca>
    </marcas>
    <oficinas>
        <oficina id="OF_BAR_02" ciudad="Barcelona">
            <vehiculo matricula="MAT1122HHH" modelo_ref="TOYO"/>
            <vehiculo matricula="MAT3344JJJ" modelo_ref="RAV_4"/>
        </oficina>
    </oficinas>
    <empleados>
        <empleado id="E_COMER_45" nombre="Roberto Cano">
            <curso nombre="Mantenimiento Híbridos" fecha="2024-05-12"/>
            <curso nombre="Sistemas de Navegación" fecha="2024-08-30"/>
        </empleado>
    </empleados>
    <clientes>
        <cliente dni="DNI99001122K" nombre="Javier López">
            <alquiler matricula_ref="MAT1122HHH" oficina_ref="OF_BAR_02" empleado_ref="E_COMER_45" fecha_inicio="2026-01-10"/>
        </cliente>
    </clientes>
</agencia>
