=== PablodelaRosa07/LDM/intro_xml/notas.dtd
<!ELEMENT diario (nombre, telefono, notes)>
<!ATTLIST diario 
    fecha_actualizacion CDATA #REQUIRED
    anyo_nacimiento CDATA #REQUIRED>

<!ELEMENT telefono (#PCDATA)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT notes (note+)>
<!ELEMENT note (to,from,heading,body)>
<!ELEMENT to (#PCDATA)>
<!ELEMENT from (#PCDATA)>
<!ELEMENT heading (#PCDATA)>
<!ELEMENT body (#PCDATA)>

=== PablodelaRosa07/LDM/intro_xml/notas.xml
<?xml version="1.0"?>
<!DOCTYPE notes SYSTEM "notas.dtd">
<diario>
<nombre></nombre>
<telefono></telefono>
<notes>
    <note>
        <to>Tove</to>
        <from>Jani</from>
        <heading>Reminder</heading>
        <body>Don't forget me this weekend</body>
    </note>
    <note>
        <to>Tove</to>
        <from>Jani</from>
        <heading>Reminder</heading>
        <body>Don't forget me this weekend</body>
    </note>
</notes>
</diario>
