=== PablodelaRosa07/LDM/ExamenLDM/Ejercicio2/Ejercicio2.dtd
<!ELEMENT Gestion (Empleados, Cargos, Proyectos)>

<!ELEMENT Empleados (Empleado+)>
<!ELEMENT Empleado (DNI, NSS, Nombre, Apellidos, Cargo, CodProyecto)>
<!ATTLIST Empleado id ID #REQUIRED>

<!ELEMENT DNI (#PCDATA)>
<!ELEMENT NSS (#PCDATA)>
<!ELEMENT Nombre (#PCDATA)>
<!ELEMENT Apellidos (#PCDATA)>
<!ELEMENT Cargo (#PCDATA)>
<!ELEMENT CodProyecto (#PCDATA)>

<!ELEMENT Cargos (EmpleadoCargo+)>
<!ELEMENT EmpleadoCargo (Sueldo)>
<!ATTLIST EmpleadoCargo nombre CDATA #REQUIRED
            categoria (Administracion | Direccion) "Direccion">

<!ELEMENT Sueldo (#PCDATA)>

<!ELEMENT Proyectos (Proyecto+)>
<!ELEMENT Proyecto (Tipo, Sede, FechaInicio, Responsable)>
<!ATTLIST Proyecto id_pro ID #REQUIRED
            estado (Activo | Pausado | Finalizado) "Activo">

<!ELEMENT Tipo (#PCDATA)>
<!ELEMENT Sede (#PCDATA)>
<!ELEMENT FechaInicio (#PCDATA)>
<!ELEMENT Responsable (#PCDATA)>

=== PablodelaRosa07/LDM/ExamenLDM/Ejercicio2/CasoA.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Gestion SYSTEM "Ejercicio2.dtd">
<Gestion>
    <Empleados>
        <Empleado id="E1">
            <DNI>27663377L</DNI>
            <NSS>420000023040</NSS>
            <Nombre>Juan</Nombre>
            <Apellidos>Ramirez López</Apellidos>
            <Cargo>Técnico</Cargo>
            <CodProyecto>P1</CodProyecto>
        </Empleado>
    </Empleados>

    <Cargos>
        <EmpleadoCargo nombre="Técnico" categoria="Direccion">
            <Sueldo>1700</Sueldo>
        </EmpleadoCargo>
    </Cargos>

    <Proyectos>
        <Proyecto id_pro="P1" estado="Activo">
            <Tipo>Desarrollo</Tipo>
            <Sede>Sevilla</Sede>
            <FechaInicio>14/03/2026</FechaInicio>
            <Responsable>Manuela López</Responsable>
        </Proyecto>
    </Proyectos>
</Gestion>

=== PablodelaRosa07/LDM/ExamenLDM/Ejercicio2/CasoB.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Gestion SYSTEM "Ejercicio2.dtd">
<Gestion>
    <Empleados>
        <Empleado id="E1">
            <DNI>27663377L</DNI>
            <NSS>420000023040</NSS>
            <Nombre>Juan</Nombre>
            <Apellidos>Ramirez López</Apellidos>
            <Cargo>Técnico</Cargo>
            <CodProyecto>P1</CodProyecto>
        </Empleado>
        <Empleado id="E2">
            <DNI>32998877K</DNI>
            <NSS>420000023232</NSS>
            <Nombre>Ana</Nombre>
            <Apellidos>García León</Apellidos>
            <Cargo>Líder</Cargo>
            <CodProyecto>P1</CodProyecto>
        </Empleado>
        <Empleado id="E3">
            <DNI>98889993H</DNI>
            <NSS>420000013252</NSS>
            <Nombre>Javier</Nombre>
            <Apellidos>Sanz Amigo</Apellidos>
            <Cargo>Líder</Cargo>
            <CodProyecto>P2</CodProyecto>
        </Empleado>
        <Empleado id="E4">
            <DNI>11002233J</DNI>
            <NSS>420000042368</NSS>
            <Nombre>Fatima</Nombre>
            <Apellidos>Pérez García</Apellidos>
            <Cargo>Técnico</Cargo>
            <CodProyecto>P2</CodProyecto>
        </Empleado>
    </Empleados>

    <Cargos>
        <EmpleadoCargo nombre="Técnico" categoria="Administracion">
            <Sueldo>1700</Sueldo>
        </EmpleadoCargo>
        <EmpleadoCargo nombre="Líder" categoria="Direccion">
            <Sueldo>2600</Sueldo>
        </EmpleadoCargo>
    </Cargos>

    <Proyectos>
        <Proyecto id_pro="P1" estado="Activo">
            <Tipo>Desarrollo</Tipo>
            <Sede>Sevilla</Sede>
            <FechaInicio>14/03/2026</FechaInicio>
            <Responsable>Manuela López</Responsable>
        </Proyecto>
        <Proyecto id_pro="P2" estado="Activo">
            <Tipo>Mantenimiento</Tipo>
            <Sede>Madrid</Sede>
            <FechaInicio>08/05/2026</FechaInicio>
            <Responsable>José Rodriguez</Responsable>
        </Proyecto>
    </Proyectos>
</Gestion>
