=== PablodelaRosa07/LDM/EXAMEN LDM/xml_dtd/Ejercicio2/Biblioteca.dtd
<!ELEMENT campus (usuarios, materiales, personal, prestamos)>

<!ELEMENT usuarios (usuario+)>
<!ELEMENT usuario EMPTY>
<!ATTLIST usuario 
          id_estudiante ID #REQUIRED
          nombre CDATA #REQUIRED
          nivel (GS | Universitario | Master) #REQUIRED
          estado (Activo | Bloqueado) "Activo">

<!ELEMENT materiales (material+)>
<!ELEMENT material EMPTY>
<!ATTLIST material 
          id_material ID #REQUIRED
          titulo CDATA #REQUIRED
          tipo (Libro | Camara) #REQUIRED
          dias_prestamo_max CDATA #REQUIRED>

<!ELEMENT personal (empleado+)>
<!ELEMENT empleado EMPTY>
<!ATTLIST empleado 
          id_empleado ID #REQUIRED
          nombre CDATA #REQUIRED
          departamento (Biblioteca | Servicio_Tecnico) #REQUIRED>

<!ELEMENT prestamos (prestamo+)>
<!ELEMENT prestamo EMPTY>
<!ATTLIST prestamo 
          id_p ID #REQUIRED
          usuario_ref IDREF #REQUIRED
          material_ref IDREF #REQUIRED
          empleado_ref IDREF #REQUIRED
          sede_recogida (Porvenir | Cartuja) #REQUIRED
          sede_devolucion (Porvenir | Cartuja) #IMPLIED
          fecha_salida CDATA #REQUIRED
          fecha_limite CDATA #REQUIRED>

=== PablodelaRosa07/LDM/Pablo_delaRosa_AE_U5.1/Ejercicio2/CasoA.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE campus SYSTEM "Biblioteca.dtd">
<campus>
    <usuarios>
        <usuario id_estudiante="ALU001" nombre="Ana Silva" nivel="GS" estado="Activo"/>
    </usuarios>
    <materiales>
        <material id_material="LIB45" titulo="XML para Principiantes" tipo="Libro" dias_prestamo_max="7"/>
    </materiales>
    <personal>
        <empleado id_empleado="EMP01" nombre="Juan Bibliotecario" departamento="Biblioteca"/>
    </personal>
    <prestamos>
        <prestamo id_p="P001" usuario_ref="ALU001" material_ref="LIB45" empleado_ref="EMP01" 
                  sede_recogida="Cartuja" fecha_salida="2026-03-01" fecha_limite="2026-03-08"/>
    </prestamos>
</campus>

=== PablodelaRosa07/LDM/EXAMEN LDM/xml_dtd/Ejercicio2/CasoB.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE campus SYSTEM "Biblioteca.dtd">
<campus>
    <usuarios>
        <usuario id_estudiante="ALU002" nombre="Luis García" nivel="Master" estado="Bloqueado"/>
    </usuarios>
    <materiales>
        <material id_material="CAM09" titulo="Sony PS" tipo="Camara" dias_prestamo_max="3"/>
    </materiales>
    <personal>
        <empleado id_empleado="EMP02" nombre="Sonia Tecnica" departamento="Servicio_Tecnico"/>
    </personal>
    <prestamos>
        <prestamo id_p="P002" usuario_ref="ALU002" material_ref="CAM09" empleado_ref="EMP02" 
                  sede_recogida="Porvenir" sede_devolucion="Cartuja" 
                  fecha_salida="2026-02-15" fecha_limite="2026-02-18"/>
    </prestamos>
</campus>
